server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy /api/* to the save-api sidecar
    location /api/ {
        proxy_pass http://helix-design-api:8080/;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
